import { Character } from './types';

export const MOCK_CHARACTERS: Character[] = [
  {
    id: '1',
    name: '芙宁娜',
    company: '米哈游',
    game: '原神',
    version: '4.2',
    rarity: 'SSR',
    position: '副C/辅助',
    weaponType: '单手剑',
    tags: ['水元素', '枫丹', '神性'],
    status: '已上线',
    createTime: '2023-05-10',
    launchTime: '2023-11-08',
    worldview: '枫丹廷的女王，众水、众方、众律法的女王。',
    background: '在枫丹的审判庭上，她总是最引人注目的焦点。',
    personality: '戏剧化、优雅、内心深处藏着巨大的秘密。',
    sellingPoints: '独特的荒芒切换机制，全队增伤，召唤物自动攻击。',
    assets: {
      portrait: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/1-furina/illustration/main.png',
      conceptArt: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/1-furina/illustration/main.png',
      modelPreview: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/1-furina/model-3d/model.glb',
      pvUrl: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/1-furina/pv/launch.mp4'
    },
    progress: {
      concept: true,
      illustration: true,
      modeling: true,
      skills: true,
      stats: true,
      voice: true,
      pv: true,
      config: true,
      marketing: true,
    },
    overallProgress: 100,
    currentStage: '已归档',
    nextMilestone: '-',
    isDelayed: false,
    riskNote: '无',
    performance: {
      firstDayRevenue: 45000000,
      firstThreeDaysRevenue: 120000000,
      firstWeekRevenue: 210000000,
      peakPopularity: 98,
      rank: 1,
      revenueTrend: [
        { date: 'Day 1', value: 4500 },
        { date: 'Day 2', value: 3800 },
        { date: 'Day 3', value: 3700 },
        { date: 'Day 4', value: 2500 },
        { date: 'Day 5', value: 2200 },
        { date: 'Day 6', value: 2100 },
        { date: 'Day 7', value: 2200 },
      ],
      popularityTrend: [
        { date: 'Day 1', value: 98 },
        { date: 'Day 2', value: 95 },
        { date: 'Day 3', value: 96 },
        { date: 'Day 4', value: 92 },
        { date: 'Day 5', value: 90 },
        { date: 'Day 6', value: 88 },
        { date: 'Day 7', value: 89 },
      ],
    },
    review: {
      summary: '流水与热度双爆表，剧情加成极大，机制设计成功。',
      tag: '表现优秀',
    },
  },
  {
    id: '2',
    name: '黄泉',
    company: '米哈游',
    game: '崩坏：星穹铁道',
    version: '2.1',
    rarity: 'SSR',
    position: '主C',
    weaponType: '太刀',
    tags: ['虚无', '雷元素', '巡海游侠'],
    status: '已上线',
    createTime: '2023-08-15',
    launchTime: '2024-03-27',
    worldview: '自称为「巡海游侠」的旅人，本名不详。',
    background: '身佩长刀，独行银河，寻找着某种终结。',
    personality: '沉默寡言、冷酷、内心深处有着坚定的信念。',
    sellingPoints: '无视弱点削韧，终结技爆发极高，独特的残梦机制。',
    assets: {
      portrait: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/2-acheron/illustration/800px-黄泉立绘3.jpg',
      conceptArt: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/2-acheron/illustration/800px-黄泉立绘3.jpg',
      modelPreview: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/2-acheron/model-3d/out.glb',
      pvUrl: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/2-acheron/pv/ogIACmdECBibxgFUohELYy7AeMMsfARixB2lrN.mp4'
    },
    progress: {
      concept: true,
      illustration: true,
      modeling: true,
      skills: true,
      stats: true,
      voice: true,
      pv: true,
      config: true,
      marketing: true,
    },
    overallProgress: 100,
    currentStage: '已归档',
    nextMilestone: '-',
    isDelayed: false,
    riskNote: '无',
    performance: {
      firstDayRevenue: 52000000,
      firstThreeDaysRevenue: 140000000,
      firstWeekRevenue: 250000000,
      peakPopularity: 99,
      rank: 1,
      revenueTrend: [
        { date: 'Day 1', value: 5200 },
        { date: 'Day 2', value: 4500 },
        { date: 'Day 3', value: 4300 },
        { date: 'Day 4', value: 3000 },
        { date: 'Day 5', value: 2800 },
        { date: 'Day 6', value: 2600 },
        { date: 'Day 7', value: 2600 },
      ],
      popularityTrend: [
        { date: 'Day 1', value: 99 },
        { date: 'Day 2', value: 98 },
        { date: 'Day 3', value: 97 },
        { date: 'Day 4', value: 95 },
        { date: 'Day 5', value: 94 },
        { date: 'Day 6', value: 92 },
        { date: 'Day 7', value: 93 },
      ],
    },
    review: {
      summary: '星铁目前流水巅峰，角色人气极高，动画演出震撼。',
      tag: '表现优秀',
    },
  },
  {
    id: '3',
    name: '艾莲',
    company: '米哈游',
    game: '绝区零',
    version: '1.0',
    rarity: 'SSR',
    position: '强攻',
    weaponType: '剪刀',
    tags: ['冰元素', '维多利亚家政'],
    status: '已上线',
    createTime: '2023-10-10',
    launchTime: '2024-07-04',
    worldview: '维多利亚家政的执事，有着鲨鱼特征。',
    background: '在战斗中展现出极高的效率和冷酷。',
    personality: '慵懒、高效、对甜食有执念。',
    sellingPoints: '极速位移，高频冰伤，独特的巡游机制。',
    assets: {
      portrait: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/3-ellen-joe/illustration/bnnfnp3tyyt7shlqhqnfsokomofn5l4.png',
      conceptArt: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/3-ellen-joe/illustration/bnnfnp3tyyt7shlqhqnfsokomofn5l4.png',
      modelPreview: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/3-ellen-joe/model-3d/output.glb',
      pvUrl: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/3-ellen-joe/pv/oUhgfOlDBxpflE2fZE63AIRZLWK0CAxVI7CMZ9.mp4'
    },
    progress: {
      concept: true,
      illustration: true,
      modeling: true,
      skills: true,
      stats: true,
      voice: true,
      pv: true,
      config: true,
      marketing: true,
    },
    overallProgress: 100,
    currentStage: '已归档',
    nextMilestone: '-',
    isDelayed: false,
    riskNote: '无',
    performance: {
      firstDayRevenue: 35000000,
      firstThreeDaysRevenue: 85000000,
      firstWeekRevenue: 150000000,
      peakPopularity: 92,
      rank: 1,
      revenueTrend: [
        { date: 'Day 1', value: 3500 },
        { date: 'Day 2', value: 3000 },
        { date: 'Day 3', value: 2000 },
        { date: 'Day 4', value: 1800 },
        { date: 'Day 5', value: 1600 },
        { date: 'Day 6', value: 1500 },
        { date: 'Day 7', value: 1600 },
      ],
      popularityTrend: [
        { date: 'Day 1', value: 92 },
        { date: 'Day 2', value: 90 },
        { date: 'Day 3', value: 88 },
        { date: 'Day 4', value: 85 },
        { date: 'Day 5', value: 84 },
        { date: 'Day 6', value: 82 },
        { date: 'Day 7', value: 83 },
      ],
    },
    review: {
      summary: '开服首个限定，表现符合预期，角色设计非常吸粉。',
      tag: '表现稳定',
    },
  },
  {
    id: '4',
    name: '忌炎',
    company: '库洛游戏',
    game: '鸣潮',
    version: '1.0',
    rarity: 'SSR',
    position: '主C',
    weaponType: '重刃',
    tags: ['气动', '瑝珑', '夜归团长'],
    status: '已上线',
    createTime: '2023-06-15',
    launchTime: '2024-05-23',
    worldview: '夜归军团的团长，守护着瑝珑的边境。',
    background: '在战场上如青龙般降临，统领全局。',
    personality: '沉稳、果断、富有责任感。',
    sellingPoints: '大范围聚怪，变身机制，华丽的青龙特效。',
    assets: {
      portrait: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/4-jiyan/illustration/微信图片_20260504151617_977_85.png',
      conceptArt: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/4-jiyan/illustration/微信图片_20260504151617_977_85.png',
      modelPreview: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&h=800&auto=format&fit=crop',
      pvUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&h=675&auto=format&fit=crop'
    },
    progress: {
      concept: true,
      illustration: true,
      modeling: true,
      skills: true,
      stats: true,
      voice: true,
      pv: true,
      config: true,
      marketing: true,
    },
    overallProgress: 100,
    currentStage: '已归档',
    nextMilestone: '-',
    isDelayed: false,
    riskNote: '无',
    performance: {
      firstDayRevenue: 28000000,
      firstThreeDaysRevenue: 65000000,
      firstWeekRevenue: 110000000,
      peakPopularity: 88,
      rank: 3,
      revenueTrend: [
        { date: 'Day 1', value: 2800 },
        { date: 'Day 2', value: 2200 },
        { date: 'Day 3', value: 1500 },
        { date: 'Day 4', value: 1200 },
        { date: 'Day 5', value: 1100 },
        { date: 'Day 6', value: 1000 },
        { date: 'Day 7', value: 1200 },
      ],
      popularityTrend: [
        { date: 'Day 1', value: 88 },
        { date: 'Day 2', value: 85 },
        { date: 'Day 3', value: 82 },
        { date: 'Day 4', value: 80 },
        { date: 'Day 5', value: 78 },
        { date: 'Day 6', value: 75 },
        { date: 'Day 7', value: 76 },
      ],
    },
    review: {
      summary: '鸣潮开服首个限定，虽然受到开服舆论影响，但角色本身素质过硬。',
      tag: '表现稳定',
    },
  },
  {
    id: '5',
    name: '阿米娅',
    company: '鹰角网络',
    game: '明日方舟',
    version: '1.0',
    rarity: 'SSR',
    position: '术师/近卫',
    weaponType: '法术/剑',
    tags: ['罗德岛', '领袖', '奇美拉'],
    status: '已上线',
    createTime: '2019-01-01',
    launchTime: '2019-05-01',
    worldview: '罗德岛的公开领袖。',
    background: '在残酷的世界中寻找着感染者的未来。',
    personality: '坚强、温柔、背负着沉重的使命。',
    sellingPoints: '多职业切换，真实伤害，剧情核心。',
    assets: {
      portrait: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/5-amiya/illustration/o8ckif3rqc1ssxvv5cmrmcj3y9p4b1t.png',
      conceptArt: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/5-amiya/illustration/o8ckif3rqc1ssxvv5cmrmcj3y9p4b1t.png',
      modelPreview: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1200&h=800&auto=format&fit=crop',
      pvUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1200&h=675&auto=format&fit=crop'
    },
    progress: {
      concept: true,
      illustration: true,
      modeling: true,
      skills: true,
      stats: true,
      voice: true,
      pv: true,
      config: true,
      marketing: true,
    },
    overallProgress: 100,
    currentStage: '已归档',
    nextMilestone: '-',
    isDelayed: false,
    riskNote: '无',
    performance: {
      firstDayRevenue: 15000000,
      firstThreeDaysRevenue: 35000000,
      firstWeekRevenue: 60000000,
      peakPopularity: 95,
      rank: 5,
      revenueTrend: [
        { date: 'Day 1', value: 1500 },
        { date: 'Day 2', value: 1200 },
        { date: 'Day 3', value: 800 },
        { date: 'Day 4', value: 700 },
        { date: 'Day 5', value: 600 },
        { date: 'Day 6', value: 600 },
        { date: 'Day 7', value: 600 },
      ],
      popularityTrend: [
        { date: 'Day 1', value: 95 },
        { date: 'Day 2', value: 94 },
        { date: 'Day 3', value: 93 },
        { date: 'Day 4', value: 92 },
        { date: 'Day 5', value: 91 },
        { date: 'Day 6', value: 90 },
        { date: 'Day 7', value: 91 },
      ],
    },
    review: {
      summary: '方舟的标志性角色，长线运营的基石。',
      tag: '表现优秀',
    },
  },
  {
    id: '6',
    name: '佩丽卡',
    company: '鹰角网络',
    game: '明日方舟：终末地',
    version: '测试版',
    rarity: 'SSR',
    position: '管理员',
    weaponType: '长剑',
    tags: ['终末地工业', '协议回收部门'],
    status: '开发中',
    createTime: '2023-03-15',
    worldview: '终末地工业协议回收部门的管理员。',
    background: '在塔洛斯II星上开拓新的家园。',
    personality: '理智、果敢、神秘。',
    sellingPoints: '3D即时战斗，基建建设核心。',
    assets: {
      portrait: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=800&h=800&auto=format&fit=crop',
      conceptArt: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&h=800&auto=format&fit=crop',
      modelPreview: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1200&h=800&auto=format&fit=crop',
      pvUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=1200&h=675&auto=format&fit=crop'
    },
    progress: {
      concept: true,
      illustration: true,
      modeling: true,
      skills: true,
      stats: false,
      voice: false,
      pv: true,
      config: false,
      marketing: false,
    },
    overallProgress: 55,
    currentStage: '数值平衡/配音',
    nextMilestone: '首测开启',
    isDelayed: false,
    riskNote: '3D大世界适配工作量大',
  },
  {
    id: '7',
    name: '砂金',
    company: '米哈游',
    game: '崩坏：星穹铁道',
    version: '2.1',
    rarity: 'SSR',
    position: '存护',
    weaponType: '筹码',
    tags: ['虚数', '星际和平公司', '战略投资部'],
    status: '已上线',
    createTime: '2023-09-10',
    launchTime: '2024-04-17',
    worldview: '星际和平公司「战略投资部」的高级干部。',
    background: '游走于生死边缘的豪赌客。',
    personality: '自信、狡黠、内心深处有着孤独的过往。',
    sellingPoints: '强力群体护盾，追加攻击，独特的盲注机制。',
    assets: {
      portrait: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/7-aventurine/illustration/image.png',
      conceptArt: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/7-aventurine/illustration/image.png',
      modelPreview: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/7-aventurine/model-3d/out.glb',
      pvUrl: 'https://jthwds.oss-cn-hangzhou.aliyuncs.com/characters/7-aventurine/pv/oEQUf5QoI7k35J1Ad4mEdMKBHEEoNfDhgLFyEF.mp4'
    },
    progress: {
      concept: true,
      illustration: true,
      modeling: true,
      skills: true,
      stats: true,
      voice: true,
      pv: true,
      config: true,
      marketing: true,
    },
    overallProgress: 100,
    currentStage: '已归档',
    nextMilestone: '-',
    isDelayed: false,
    riskNote: '无',
    performance: {
      firstDayRevenue: 32000000,
      firstThreeDaysRevenue: 75000000,
      firstWeekRevenue: 130000000,
      peakPopularity: 94,
      rank: 2,
      revenueTrend: [
        { date: 'Day 1', value: 3200 },
        { date: 'Day 2', value: 2800 },
        { date: 'Day 3', value: 1500 },
        { date: 'Day 4', value: 1400 },
        { date: 'Day 5', value: 1300 },
        { date: 'Day 6', value: 1400 },
        { date: 'Day 7', value: 1400 },
      ],
      popularityTrend: [
        { date: 'Day 1', value: 94 },
        { date: 'Day 2', value: 93 },
        { date: 'Day 3', value: 92 },
        { date: 'Day 4', value: 90 },
        { date: 'Day 5', value: 89 },
        { date: 'Day 6', value: 88 },
        { date: 'Day 7', value: 89 },
      ],
    },
    review: {
      summary: '剧情表现极其出彩，成功反转口碑，流水表现远超预期。',
      tag: '表现优秀',
    },
  },
];
